version: "3.8"

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    volumes:
      - ./auth:/app # Auth loyihasi uchun bind mount
      - /app/node_modules # Konteyner ichidagi node_modules papkasini bind mount qilmaslik
    ports:
      - "5173:5173"
    command: pnpm run dev -- --host

  home:
    build:
      context: ./home
      dockerfile: Dockerfile
    volumes:
      - ./home:/app # Home loyihasi uchun bind mount
      - /app/node_modules # Konteyner ichidagi node_modules papkasini bind mount qilmaslik
    ports:
      - "5174:5173"
    command: pnpm run dev -- --host

  common:
    build:
      context: ./common
      dockerfile: Dockerfile
    volumes:
      - ./common:/app # Home loyihasi uchun bind mount
      - /app/node_modules # Konteyner ichidagi node_modules papkasini bind mount qilmaslik
    ports:
      - "5175:5175"
    command: pnpm run dev -- --host
