services:
  auth:
    build:
      context: ./auth
    ports:
      - "3001:3000"
    volumes:
      - ./auth:/app

  home:
    build:
      context: ./home
    ports:
      - "3002:3000"
    volumes:
      - ./home:/app

  # shared-ui:
  #   build:
  #     context: ./shared-ui
  #   ports:
  #     - "3003:3000"
  #   volumes:
  #     - ./shared-ui:/app
